name: Build and Test Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

          
      # 2. Build the Docker image using your Dockerfile
      - name: Build Docker Image
        env: 
          MLFINLAB_API_KEY: ${{ secrets.MLFINLAB_API_KEY }}
          REPOSITORY_HANDLER_URL: ${{ secrets.REPOSITORY_HANDLER_URL }}
        run: |
          docker build \
            --build-arg MLFINLAB_API_KEY="${MLFINLAB_API_KEY}" \
            --build-arg REPOSITORY_HANDLER_URL="${REPOSITORY_HANDLER_URL}" \
            -t qml-manjaro \
            .

      # 3. Run the test suite inside a container based on the image.
      #    Here, we mount the repository into the container at /workspace,
      #    set the working directory to /workspace, and run the test command.
      - name: Run Test Suite
        env: 
          MLFINLAB_API_KEY: ${{ secrets.MLFINLAB_API_KEY }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /workspace \
            qml-manjaro \
            /bin/bash -c "echo \'its working\'"
